name: CI

on:
  push:
    branches:
      - main
      - master
      - assignment
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./web
      - name: Lint
        run: yarn lint
        working-directory: ./web

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./web
      - name: Run Tests
        run: yarn test
        working-directory: ./web
